// vue2-main/src/App.jsx
import Cookies from "js-cookie";
import { CRMSESSID } from "@/config";
import microApp from "@micro-zoe/micro-app";

export default {
  mounted() {
    const token = Cookies.get(CRMSESSID);
    if (token) {
      microApp.setGlobalData({
        token,
      });
    }
  },
  render() {
    return (
      <div id="app">
        <router-view />
        {/* <micro-app name="vue3-child" url="http://localhost:8081/"></micro-app> */}
        {/* <micro-app name="react-child" url="http://localhost:3001/"></micro-app>
        <micro-app
          name="vue3-main"
          iframe
          url="http://localhost:5000/"
        ></micro-app> */}
      </div>
    );
  },
};

// vue3-vite-child/src/App.jsx
import { defineComponent, onMounted } from "vue";
import Cookies from "js-cookie";

export default defineComponent({
  setup() {
    onMounted(() => {
      if (window.microApp) {
        const data = window.microApp.getGlobalData() || {};
        console.log("data", data);
        Cookies.set("CRMSESSID", data.token);
      }
    });
  },
  render() {
    return (
      <div>
        <a-config-provider prefixCls={"vue3-vite-child-ant"}>
          <router-view />
        </a-config-provider>
      </div>
    );
  },
});
